# Generated by Django 5.2.4 on 2025-07-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('SF', 'SF'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Horror', 'Horror')], max_length=50),
        ),
    ]
